### ISSUE TITLE
Plan trip is broken for me

### ISSUE THREAD

**Issue by pastelApe** [CMSC495-Team1/Team1_TripPlanner#18]
@GChel31 I forked the repo to start working on somethings. When I ran the app just to make sure it worked the plan trip page looks like this. Is it working for you?

<img width="1605" alt="Screenshot 2024-11-11 at 9 55 26 PM" src="https://github.com/user-attachments/assets/15c01a15-5ff9-426a-b0f5-13760fd77e15">

**Comment by GChel31** [comment]
No

**Comment by GChel31** [comment]
Sorry, hit the wrong button on my phone. Im going to double check the
current files, but my copies work

**Comment by GChel31** [comment]
Just checked the files and am getting the same result. Will look into it right now

**Comment by pastelApe** [comment]
Thanks. No rush. I'll check back in tomorrow.

**Comment by GChel31** [comment]
I found the issue. The table in the database that had all of the destination info is now empty, so all of the things that should be populating most of that page are not there.

**Comment by GChel31** [comment]
I reverted the db in my latest update. The current version should be working now.
