### ISSUE TITLE
Registration and login form input fields not displaying inline. 

### ISSUE THREAD

**Issue by pastelApe** [CMSC495-Team1/Team1_TripPlanner#34]
Hey Greg, 

I made a new registration and login form, but for some reason the username fields is messed up. 
![image](https://github.com/user-attachments/assets/3a2b1a3a-cba5-421e-b234-56d6e9f25e67)

Also, could you look at the logout button and tie into the log out route please. I couldn't figure it out. I haven't used javascript before and sing inline html was throwing me off for some reason.

**Comment by pastelApe** [comment]
I now have the logout button working, except for redirecting to the index page.

**Comment by GChel31** [comment]
All forms are now inline
