### ISSUE TITLE
Database migration issues

### ISSUE THREAD

**Issue by pastelApe** [CMSC495-Team1/Team1_TripPlanner#35]
Multiple issues reported from the team. Refactored the project to use the default instance directory created by the flask app. Moved the db creation into it. The old instance folder is now just data and hold the json and `import_data` module. Models have been moved into `app/`.

**Comment by pastelApe** [comment]
The app factory (`__init__`) is now far more robust. 

First time pulling the repo:
Migrations and database generated 

Deleted the db?
Running the app recreates the db

Deleted the migrations folder?
Running the app recreates the migrations

Deleted Both?
You get the idea 🤗

**Comment by tbizz46** [comment]
This approach aligns well with best practices in software deployment and continuous integration. Great job.
